version: '3.1'

services:

  app:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    networks:
      source:
        aliases:
          - app

#  nginx:
#    container_name: nginx
#    image: nginx
#    build:
#      context: ./nginx
#      dockerfile: nginx.dockerfile
#    volumes:
#      - ../usr/src/app/frontend/dist:/usr/share/nginx/html
#    ports:
#      - 80:80
#    depends_on:
#      - app
#    networks:
#      source:
#        aliases:
#          - web

networks:
  source:
