version: '3.1'

services:

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ../:/usr/src/app/frontendv
      - ../:/usr/share/nginx/html
    working_dir: /usr/src/app/frontend
    networks:
      source:
        aliases:
          - app

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    volumes:
      - ../:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      source:
        aliases:
          - web

networks:
  source:
