server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://109717:eyJrIjoiYjAzNjVlMGUxOGRhM2U2ZTQ5OTk3M2E5ZDkyODFjMDA3Y2I1NWM1YSIsIm4iOiJOZXN0IEhvbWUiLCJpZCI6NTUwMDkwfQ==@logs-prod-eu-west-0.grafana.net/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
