server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: GRAFANA_URL

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          node_env: ${NODE_ENV}
          __path__: /var/log/system.log
  - job_name: nest-home-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          node_env: ${NODE_ENV}
          __path__: ./logs/backend-*.log
  - job_name: nest-home-frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend
          node_env: ${NODE_ENV}
          __path__: ./logs/frontend-*.log
  - job_name: nest-home-sonos
    static_configs:
      - targets:
          - localhost
        labels:
          job: sonos
          node_env: ${NODE_ENV}
          __path__: ./logs/sonos-*.log
  - job_name: nest-home-promtail
    static_configs:
      - targets:
          - localhost
        labels:
          job: promtail
          node_env: ${NODE_ENV}
          __path__: ./logs/promtail-*.log
